const API_ENDPOINTS = {
    customerAuthIndex: "/api/customer/auth/index",
    customerAuthSignup: "/api/customer/auth/signup",
    customerAuthLogin: "/api/customer/auth/login",
    customerAuthLogout: "/api/customer/auth/logout",
    customerAuthChangePassword: "/api/customer/auth/change_password",
    customerIndex: "/api/customer/index",
    customerService: "/api/customer/customer_service",
    customerSignupDetails: "/api/customer/signup/customer_details",
    customerProfile: "/api/customer/profile",
    customerProfileUpdate: "/api/customer/profile/update",
    customerProfileUpload: "/api/customer/profile/upload",
    customerViewProfileImage: "/api/customer/profile/view_profile_image",
    customerSendMoney: "/api/customer/send_money",
    customerCashOut: "/api/customer/cash_out",
    customerBillPayment: "/api/customer/bill_payment",
    customerCashIn: "/api/customer/cash_in",
    customerWalletToBank: "/api/customer/add_money/wallet_to_bank",
    customerWalletToCard: "/api/customer/add_money/wallet_to_card",
    customerBankToWallet: "/api/customer/add_money/bank_to_wallet",
    customerPaymentList: "/api/customer/payment/list",
    customerPaymentCashInList: "/api/customer/payment/list/cash_in",
    customerForgetPassword: "/api/customer/forget_password",
    customerOTP: "/api/customer/otp",
    navbarInfo: "/api/customer/navbar_info",
};

export default API_ENDPOINTS;
